# Create an Azure Image Builder template.

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for required variables
      assert:
        that:
          - profile is defined

    - name: Load configuration
      include_vars:
        file: image/configurations/{{ profile }}.yml

    - name: Load and populate the template
      include_vars:
        file: image/template.yml
        name: template

    - name: Write the template file to disk
      copy:
        content: "{{ template | to_nice_json }}\n"
        dest: image/templates/{{ profile }}.json
        mode: 0644
