# Create a virtual machine scale set for use with Azure Pipelines.

- hosts: localhost
  gather_facts: no
  vars:
    username: "ubuntu"
    scaleset: "AgentPool-{{ vm_size }}-{{ scaleset_region }}"
    virtual_network: "Network-{{ scaleset_region }}"
    subnet: "AgentPool-{{ vm_size }}"
    image: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/galleries/{{ gallery }}/images/{{ profile }}/versions/{{ image_version }}"
  tasks:
    - name: Check for required variables
      assert:
        that:
          - scaleset_region is defined
          - scaleset_resource_group is defined
          - vm_size is defined
          - profile is defined
          - image_version is defined
          - password is defined

    - name: Create a virtual machine scale set
      command: az vmss create
        --name "{{ scaleset }}"
        --vnet-name "{{ virtual_network }}"
        --vm-sku "{{ vm_size }}"
        --subnet "{{ subnet }}"
        --subscription {{ subscription_id }}
        --resource-group {{ scaleset_resource_group }}
        --location {{ scaleset_region }}
        --image {{ image }}
        --authentication-type password
        --admin-username "{{ username }}"
        --admin-password "{{ password }}"
        --storage-sku Standard_LRS
        --instance-count 0
        --disable-overprovision
        --upgrade-policy-mode manual
        --single-placement-group false
        --platform-fault-domain-count 1
        --load-balancer ""
        --ephemeral-os-disk true
        --os-disk-caching readonly
        --accelerated-networking "{{ accelerated_networking | default(false) | string | lower }}"
      register: vmss_create

    - name: Parse virtual machine scale set information
      set_fact:
        vm: "{{ vmss_create.stdout | from_json }}"
