# Create an Azure Image Builder template.

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for required variables
      assert:
        that:
          - profile is defined

    - name: Load configuration
      include_vars:
        file: image/configurations/{{ profile }}.yml

    - name: Check out ansible/ansible and pull branch updates
      git:
        repo: https://github.com/ansible/ansible
        dest: "{{ git_cache_path }}/{{ item }}"
        version: "{{ item }}"
      loop: "{{ branches }}"
      tags:
        - git

    - name: Collect docker pull commands from ansible-test container image usage
      set_fact:
        docker_pull: "{{ lookup('annotated_pull_commands', branches=branches, git_cache_path=git_cache_path) }}"

    - name: Load and populate the template
      include_vars:
        file: image/template.yml
        name: template

    - name: Write the template file to disk
      copy:
        content: "{{ template | to_nice_json }}\n"
        dest: image/templates/{{ profile }}.json
        mode: 0644
