# Create an Azure Image Builder for use with ansible-test on Azure Pipelines.
# This playbook assumes the features necessary for Azure Image Builder have already been registered.
# See: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-gallery#register-the-features

- hosts: localhost
  gather_facts: no
  vars:
    role_definition_name: Image Builder Service Role
  tasks:
    - name: Create the resource group
      command: az group create --subscription {{ subscription_id }} --name {{ resource_group }}
               --location {{ build_region }}

    - name: Create the user-assigned identity
      command: az identity create --subscription {{ subscription_id }} --resource-group {{ resource_group }}
               --name {{ builder_identity }}

    - name: Get the user-assigned identity information
      command: az identity show --subscription {{ subscription_id }} --resource-group {{ resource_group }}
               --name {{ builder_identity }}
      register: result

    - name: Parse the user-assigned identity information
      set_fact:
        client_id: "{{ (result.stdout | from_json)['clientId'] }}"

    - name: Load the role definition template
      include_vars:
        file: builder/role-definition.yml
        name: role_definition

    - name: Write the role definition template
      copy:
        content: "{{ role_definition | to_nice_json }}\n"
        dest: builder/role-definition.json
        mode: 0644

    - name: Create the role definition
      command: az role definition create --subscription {{ subscription_id }}
               --role-definition builder/role-definition.json
      register: result
      failed_when: result.rc != 0 and 'already exists' not in result.stderr
      changed_when: result.rc == 0

    - name: Grant the role definition to the user-assigned identity
      # CAUTION: This may not work unless subscription_id is the currently active (default) subscription. Look for errors like:
      #          "Cannot find user or service principal in graph database"
      command: az role assignment create --subscription {{ subscription_id }}
               --assignee {{ client_id }}
               --role "{{ role_definition_name }}"
               --scope /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}

    - name: Create the shared image gallery
      command: az sig create --subscription {{ subscription_id }} --resource-group {{ resource_group }}
               --gallery-name {{ gallery }}
